package com.magicscience.magicsciencemod.events;

import com.magicscience.magicsciencemod.registry.ModCapabilities;
import com.mojang.logging.LogUtils;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.world.entity.player.Player;
import net.minecraftforge.event.TickEvent;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.common.Mod;
import org.slf4j.Logger;

@Mod.EventBusSubscriber
public class ManaEvents {
    private static final Logger LOGGER = LogUtils.getLogger();

    private static final String MANA_REGEN_COOLDOWN = "mana_regen_cd";
    private static final int COOLDOWN_TICKS = 40; // 2 секунды

    @SubscribeEvent
    public static void onPlayerTick(TickEvent.PlayerTickEvent event) {
        if (event.phase != TickEvent.Phase.END) return;

        Player player = event.player;
        CompoundTag data = player.getPersistentData();

        int cooldown = data.getInt(MANA_REGEN_COOLDOWN);
        if (cooldown > 0) {
            data.putInt(MANA_REGEN_COOLDOWN, cooldown - 1);
            return;
        }

        player.getCapability(ModCapabilities.MANA_CAPABILITY).ifPresent(mana -> {
            if (mana.getMana() < mana.getMaxMana()) {
                mana.addMana(1);
                data.putInt(MANA_REGEN_COOLDOWN, COOLDOWN_TICKS);
                LOGGER.info("Mana regenerated by 1: {}", mana.getMana());
            }
        });
    }
}
